"""Uiautomator2 代码生成器：UI 树优先 + 坐标兜底 + 配置驱动

回放策略：
  1. 元素数据配置匹配 → d('resourceId=...').click() 等
  2. uiautomator2 选择器 → d(text="...").click() / d(resourceId="...").click()
  3. 无选择器 → d.click(x, y) 坐标兜底

生成的脚本使用 uiautomator2 API，比 airtest/poco 更稳定。
"""
from __future__ import annotations
import os
from ..ir.action import Action
from .element_data import ELEMENT_REGISTRY


class Uia2Codegen:
    def __init__(self, **_):
        pass

    def emit(self, a: Action) -> str:
        if a.type != "touch":
            return f"# 未支持: {a.type}"

        x, y = a.target.get("value", (0, 0))
        uia = a.params.get("uia") or {}
        element_def = a.params.get("element_def")

        if element_def:
            return self._gen_by_element_def(element_def, x, y)

        if uia:
            selector = self._uia_selector(uia)
            if selector:
                return (
                    f'try:\n'
                    f'    d({selector}).click()\n'
                    f'except:\n'
                    f'    d.click({x}, {y})'
                )

        return f'd.click({x}, {y})'

    def emit_to_script(self, actions: list[Action], output_path: str):
        lines = [
            '# -*- encoding=utf8 -*-',
            '"""Auto-generated by 录制自动化插件 (uiautomator2)"""',
            'import uiautomator2 as u2',
            'import time',
            '',
            'd = u2.connect()',
            '',
            'def run():',
        ]
        for i, a in enumerate(actions):
            code = self.emit(a)
            for line in code.split('\n'):
                lines.append(f'    {line}')
            if i < len(actions) - 1:
                lines.append('    time.sleep(1)')
            lines.append('')
        lines.append('')
        lines.append('if __name__ == "__main__":')
        lines.append('    run()')

        os.makedirs(os.path.dirname(output_path) or '.', exist_ok=True)
        with open(output_path, 'w', encoding='utf-8') as f:
            f.write('\n'.join(lines))

    @staticmethod
    def _gen_by_element_def(element_name: str, x: int, y: int) -> str:
        elem = ELEMENT_REGISTRY.get(element_name)
        if not elem:
            return f'd.click({x}, {y})'

        selectors = []
        if elem.resourceId:
            selectors.append(f'resourceId="{elem.resourceId}"')
        if elem.text:
            selectors.append(f'text="{elem.text}"')
        if elem.contentDesc:
            selectors.append(f'description="{elem.contentDesc}"')
        if elem.className:
            selectors.append(f'className="{elem.className}"')
        if elem.xpath:
            selectors.append(f'xpath="{elem.xpath}"')

        if not selectors:
            return f'd.click({x}, {y})'

        selector = selectors[0]
        return (
            f'try:\n'
            f'    d({selector}).click()\n'
            f'except:\n'
            f'    d.click({x}, {y})'
        )

    _GENERIC_CLASSES = {
        "android.widget.FrameLayout",
        "android.widget.LinearLayout",
        "android.widget.RelativeLayout",
        "android.widget.ConstraintLayout",
        "androidx.constraintlayout.widget.ConstraintLayout",
        "android.view.View",
        "android.view.ViewGroup",
        "android.widget.TextView",
        "android.widget.ImageView",
        "android.widget.Button",
    }

    @staticmethod
    def _uia_selector(attrs: dict) -> str:
        if attrs.get("resourceId"):
            rid = attrs["resourceId"]
            if ":" not in rid:
                rid = rid.split(":id/")[-1] if ":id/" in rid else rid
            return f'resourceId="{rid}"'
        if attrs.get("text"):
            return f'text="{attrs["text"]}"'
        if attrs.get("contentDesc"):
            return f'description="{attrs["contentDesc"]}"'
        cls_name = attrs.get("className", "")
        if cls_name and cls_name not in Uia2Codegen._GENERIC_CLASSES:
            return f'className="{cls_name}"'
        return ""
