"""uiautomator2 脚本组装器：把代码行组装成可运行的 Python 脚本"""
from __future__ import annotations
import os


HEADER = '''# -*- encoding=utf8 -*-
"""Auto-generated by 录制自动化插件 (uiautomator2)"""
import uiautomator2 as u2
import cv2
import numpy as np
import time as _time

d = u2.connect()

# check_stop() 和 _sleep() 由调用方注入

'''

FOOTER = '''
'''


class ScriptAssembler:
    def __init__(self, output_dir: str):
        self.output_dir = output_dir
        self.main_file = os.path.join(output_dir, "script.py")
        os.makedirs(output_dir, exist_ok=True)
        from .codegen import Uia2Codegen
        self.codegen = Uia2Codegen()
        self._lines: list[tuple[str, float, str]] = []  # (code, timestamp, action_type)
        self._started = False

    def append(self, code_line: str, timestamp: float = 0.0, action_type: str = "touch"):
        if not self._started:
            self._started = True
        self._lines.append((code_line, timestamp, action_type))

    def build(self) -> str:
        parts = [HEADER]
        parts.append("def run():\n")

        for idx, (code, ts, action_type) in enumerate(self._lines):
            parts.append("    check_stop()\n")

            for l in code.split("\n"):
                parts.append(f"    {l}\n" if l.strip() else "\n")

            if idx < len(self._lines) - 1:
                next_ts = self._lines[idx + 1][1]
                next_type = self._lines[idx + 1][2]
                if ts > 0 and next_ts > 0:
                    gap = next_ts - ts
                    if action_type == "touch" and next_type == "swipe":
                        sleep_time = max(0.5, min(3.0, gap))
                    elif action_type == "swipe" and next_type == "touch":
                        sleep_time = max(0.8, min(3.0, gap))
                    else:
                        sleep_time = max(0.3, min(3.0, gap))
                    parts.append(f"    _sleep({sleep_time:.1f})\n")
                else:
                    parts.append("    _sleep(1.0)\n")

        parts.append(FOOTER)
        content = "".join(parts)
        with open(self.main_file, "w", encoding="utf-8") as f:
            f.write(content)
        return self.main_file
