"""uiautomator2 脚本组装器：把代码行组装成可运行的 Python 脚本"""
from __future__ import annotations
import os


HEADER = '''# -*- encoding=utf8 -*-
"""Auto-generated by 录制自动化插件 (uiautomator2)"""
import uiautomator2 as u2
import time

d = u2.connect()

'''

FOOTER = '''
if __name__ == "__main__":
    run()
'''


class ScriptAssembler:
    def __init__(self, output_dir: str):
        self.output_dir = output_dir
        self.main_file = os.path.join(output_dir, "script.py")
        os.makedirs(output_dir, exist_ok=True)
        from .codegen import Uia2Codegen
        self.codegen = Uia2Codegen()
        self._lines: list[str] = []
        self._started = False

    def append(self, code_line: str):
        if not self._started:
            self._started = True
        self._lines.append(code_line)

    def build(self) -> str:
        parts = [HEADER]
        parts.append("def run():\n")
        for idx, line in enumerate(self._lines):
            for l in line.split("\n"):
                parts.append(f"    {l}\n" if l.strip() else "\n")
            if idx < len(self._lines) - 1:
                parts.append("    time.sleep(1)\n")
        parts.append(FOOTER)
        content = "".join(parts)
        with open(self.main_file, "w", encoding="utf-8") as f:
            f.write(content)
        return self.main_file
